# syntax=docker/dockerfile:1
# reference:
#   https://www.gnu.org/software/libc/manual/html_node/Installation.html
#   https://github.com/jvasileff/docker-glibc-armhf-builder/blob/master/Dockerfile
#   https://github.com/sgerrand/docker-glibc-builder/issues/20
#   https://github.com/Lauri-Nomme/alpine-glibc-xb/blob/master/Dockerfile
#   https://github.com/jvasileff/alpine-pkg-glibc-armhf/blob/master/build-with-docker.sh
#
ARG IMAGEBASE=frommakefile
#
# {{{ -- download and use raspbian legacy rootfs as baseimage
FROM ${IMAGEBASE} AS raspberry-pi-os-legacy-lite-getter
RUN set -xe \
    && apk add \
        curl \
        xz \
    && mkdir /rootfs \
    && curl \
        --retry 3 --retry-all-errors \
        -fSL https://downloads.raspberrypi.org/raspios_lite_armhf/root.tar.xz | tar xJ -C /rootfs
#
FROM scratch AS baseimage
COPY --from=raspberry-pi-os-legacy-lite-getter /rootfs/ /
RUN set -xe \
    && uname -a
# }}} --
#
# {{{ -- fetch and compile source using ubuntu image
FROM baseimage as glibc-compiler
ARG GLIBCVERSION=2.31
ARG NPROC=6
#
ENV \
    DEBIAN_FRONTEND=noninteractive \
    PREFIX_DIR=/usr/glibc-compat
#
RUN set -xe \
    && apt-get update \
    && apt-get install -y build-essential curl openssl gawk bison python3 gettext texinfo \
    && mkdir -p /glibc/build \
    && echo "Using GLIBC Version: $GLIBCVERSION" \
    && curl \
        --retry 3 --retry-all-errors \
        -jSLN https://ftpmirror.gnu.org/glibc/glibc-${GLIBCVERSION}.tar.gz \
        -o /tmp/glibc-${GLIBCVERSION}.tar.gz \
    # TODO: source verification steps
    && tar xzf /tmp/glibc-${GLIBCVERSION}.tar.gz -C /glibc --strip 1 \
    && cd /glibc/build \
    && /glibc/configure \
        --prefix=${PREFIX_DIR} \
        --libdir=${PREFIX_DIR}/lib \
        --libexecdir=${PREFIX_DIR}/lib \
        # --enable-multi-arch \
        --host=armv6-linux \
        --enable-stack-protector=strong \
    && make -j${NPROC} \
    && make install \
    && tar --hard-dereference -zcf /glibc-bin-${GLIBCVERSION}.tar.gz ${PREFIX_DIR} \
    && sha512sum /glibc-bin-${GLIBCVERSION}.tar.gz > /glibc-bin-${GLIBCVERSION}.sha512sum
# }}} --
#
# {{{ -- build apk packages
FROM ${IMAGEBASE} AS glibc-alpine-builder
#
ARG APKBUILD=APKBUILD
ARG GLIBCARCH=frommakefile
ARG GLIBCVERSION=2.31
ARG GLIBC_RELEASE=0
ARG PACKAGER=woahbase
#
RUN set -xe \
    && apk add -Uu \
        alpine-sdk \
        bash \
        coreutils \
        cmake \
        libc6-compat \
        sudo \
    && adduser -G abuild -g "Alpine Package Builder" -s /bin/ash -D builder \
    && echo "builder ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers \
    && mkdir -p /packages /home/builder/package/ \
    && chown builder:abuild /packages /home/builder/package /etc/apk/keys
#
USER builder
WORKDIR /home/builder/package/
#
COPY --from=glibc-compiler /glibc-bin-${GLIBCVERSION}.tar.gz .
COPY --from=glibc-compiler /glibc-bin-${GLIBCVERSION}.sha512sum .
COPY files/${APKBUILD} ./APKBUILD
COPY files/glibc-bin.trigger .
COPY files/ld.so.conf .
COPY files/nsswitch.conf .
#
ENV \
    ABUILD_KEY_DIR=/home/builder/.abuild \
    GLIBCARCH=${GLIBCARCH} \
    GLIBCVERSION=${GLIBCVERSION} \
    REPODEST=/packages
#
RUN set -xe \
    && mkdir -p ${ABUILD_KEY_DIR} ${REPODEST}/builder \
    && openssl genrsa -out ${ABUILD_KEY_DIR}/${PACKAGER}.rsa 2048 \
    && openssl rsa -in ${ABUILD_KEY_DIR}/${PACKAGER}.rsa -pubout -out ${ABUILD_KEY_DIR}/${PACKAGER}.rsa.pub \
    && cp ${ABUILD_KEY_DIR}/${PACKAGER}.rsa.pub /etc/apk/keys/${PACKAGER}.rsa.pub \
    && echo "PACKAGER_PRIVKEY=\"${ABUILD_KEY_DIR}/${PACKAGER}.rsa\"" > ${ABUILD_KEY_DIR}/abuild.conf \
    && sed -i "s/<\${GLIBCVERSION}-checksum>/$(cat glibc-bin-${GLIBCVERSION}.sha512sum | awk '{print $1}')/" APKBUILD \
    && abuild -r \
    && find ${REPODEST}
# }}} --
#
# {{{ -- install built apk packages and generate final image
FROM ${IMAGEBASE}
#
ARG GLIBCARCH=frommakefile
ARG GLIBC_RELEASE=0
ARG GLIBCVERSION=2.31
# ARG PACKAGER=woahbase
#
# COPY --from=glibc-alpine-builder /etc/apk/keys/${PACKAGER}.rsa.pub /etc/apk/keys/${PACKAGER}.rsa.pub
COPY --from=glibc-alpine-builder /packages/builder/${GLIBCARCH}/glibc-${GLIBCVERSION}-r${GLIBC_RELEASE}.apk /tmp/
COPY --from=glibc-alpine-builder /packages/builder/${GLIBCARCH}/glibc-bin-${GLIBCVERSION}-r${GLIBC_RELEASE}.apk /tmp/
COPY --from=glibc-alpine-builder /packages/builder/${GLIBCARCH}/glibc-i18n-${GLIBCVERSION}-r${GLIBC_RELEASE}.apk /tmp/
#
RUN set -xe \
    && apk add -Uu --no-cache libstdc++ \
    && apk add --allow-untrusted --force-overwrite /tmp/glibc-*.apk \
    && ( /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true ) \
    && echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh \
    && /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib \
    # && echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' > /etc/nsswitch.conf \
    && rm -rf /var/cache/apk/* /tmp/*
    # /etc/apk/keys/${PACKAGER}.rsa.pub
# }}} --
#
ENV PATH=/usr/glibc-compat/sbin:/usr/glibc-compat/bin:${PATH}
#
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/bin/bash"]
