ARG DOCKERSRC=frommakefile
#
FROM ${DOCKERSRC}
#
RUN set -xe \
    && apk add --no-cache --purge -uU curl \
    && mkdir -p /glibc \
    && GLIBC_VERSION="$(curl -SL https://api.github.com/repos/SatoshiPortal/alpine-pkg-glibc/releases/latest | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_v__')" \
    && echo "Using GLIBC Version: ${GLIBC_VERSION}" \
    && GLIBC_KEY="https://github.com/SatoshiPortal/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/cyphernode@satoshiportal.com.rsa.pub" \
    && GLIBC_URL='https://github.com/SatoshiPortal/alpine-pkg-glibc/releases/download' \
    && curl \
        -jkSL ${GLIBC_KEY} \
        -o /etc/apk/keys/cyphernode@satoshiportal.com.rsa.pub \
    && curl \
        -jkSL ${GLIBC_URL}/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}-armhf.apk \
        -o /glibc/glibc-${GLIBC_VERSION}.apk \
    && curl \
        -jkSL ${GLIBC_URL}/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}-armhf.apk \
        -o /glibc/glibc-bin-${GLIBC_VERSION}.apk \
    && curl \
        -jkSL ${GLIBC_URL}/${GLIBC_VERSION}/glibc-i18n-${GLIBC_VERSION}-armhf.apk \
        -o /glibc/glibc-i18n-${GLIBC_VERSION}.apk \
    && apk add --update --no-cache /glibc/*.apk; \
    /usr/glibc-compat/bin/localedef --force --inputfile POSIX --charmap UTF-8 C.UTF-8 || true \
    && echo "export LANG=C.UTF-8" > /etc/profile.d/locale.sh \
    && /usr/glibc-compat/sbin/ldconfig /lib /usr/glibc-compat/lib \
    && echo 'hosts: files mdns4_minimal [NOTFOUND=return] dns mdns4' >> /etc/nsswitch.conf \
    && apk del --purge curl glibc-i18n \
    && rm -rf /var/cache/apk/* /tmp/* /glibc /etc/apk/keys/cyphernode@satoshiportal.com.rsa.pub
#
# ENTRYPOINT ["/init"]
# ENTRYPOINT ["/bin/bash"]
